eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
server:
  port: 8887
spring:
  application:
    name: azdm-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: azdm-order
    api-b:
      path: /api-b/**
      serviceId: azdm-account